grade:
  curriculo-padrao: "37203"
  curriculos: "classpath:curriculum-37203.json,classpath:curriculum-372.json"

server:
  port: 8080

spring:
  application:
    name: grade-inteligente

logging:
  level:
    com.pucminas.gradeinteligente: INFO
